# Generated by Django 2.2.24 on 2021-12-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milk_shake',
            name='m_cost',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='milk_shake',
            name='m_flavour',
            field=models.ForeignKey(default='none', on_delete=None, to='shop.Flavour', to_field='name'),
        ),
        migrations.AddField(
            model_name='milk_shake',
            name='m_ice_cream',
            field=models.ForeignKey(default='none', on_delete=None, to='shop.Ice_cream', to_field='name'),
        ),
        migrations.AddField(
            model_name='milk_shake',
            name='m_topping',
            field=models.ForeignKey(default='none', on_delete=None, to='shop.Topping', to_field='name'),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ice_cream',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='topping',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
